<<<<<<< HEAD
# mysql配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/question?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 端口配置
server:
  port: 19316
# 日志配置1
logging:
  config: classpath:logback-spring.xml
# 常量配置
weixin:
  base:
    url: https://pangyuworld.cn/weixin
springfox:
  documentation:
    swagger:
      v2:
        host: pangyuworld.cn/jj
=======
# mysql配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/question?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 端口配置
server:
  port: 19316
# 日志配置1
logging:
  config: classpath:logback-spring.xml
# 常量配置
weixin:
  base:
    url: https://pangyuworld.cn/weixin
springfox:
  documentation:
    swagger:
      v2:
        host: pangyuworld.cn/jj
>>>>>>> b8f7379a2f87c85dff051c410bc7db72fa4a160b
