# mysql配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/question
    username: chuangxin
    password: jijin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 端口配置
server:
  port: 19316
# 日志配置1
logging:
  config: classpath:logback-spring.xml
# 常量配置
weixin:
  base-url: https://pangyuworld.cn/weixin